# ===============================
# [ Spring Properties ]
# ===============================
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/webstore?user=webstore&password=webstore
  mustache:
    expose-request-attributes: true
    suffix: .html

logging:
  level:
    com:
      github:
        greatlirik:
          DEBUG
    org:
      springframework: INFO
      hibernate: ERROR

